arm_group:
  kinematics_solver: abb_irb4600_60_205_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
robot:
  kinematics_solver: abb_irb4600_60_205_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.001
